name: GitHub Actions Demo
on: 
  push:
#   pull_request:
  schedule:
    - cron: "0 3 * * 1,3,5" # Runs at 03:00 AM (UTC) every Monday, Wednesday, and Friday (Check https://crontab.tech/)
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
      - name: Git Sync Action
        uses: wei/git-sync@v3.0.0
        with:
          source_repo: "git@github.com:szemyd/packaging-python.git"
          source_branch: "main"
          destination_repo: "git@github.com:szemyd/packaging-python-public.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key:  ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY` 
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: strip
          environment-file: strip_action.yaml
          python-version: 3.9
      - uses: iterative/setup-cml@v1
      - name: Run empty function
        shell: bash -l {0}
        run: |
          python -m libcst.tool codemod replace_functions.ReplaceFunctionCommand .
      - name: Commit and push changes
        run: |
          git config --global user.name "szemyd"
          git config --global user.email "szemy2@gmail.com"

          git add -A
          git commit -m "Stripped functions"
          git push
